name: Terraform CI/CD
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
env:
  TERRAFORM_VERSION: '1.12.1'
  LOCALSTACK_VERSION: '4.4.0'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - name: Setup LocalStack
      run: pip install localstack==${{ env.LOCALSTACK_VERSION }}
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: ap-southeast-1
    - name: Terraform Validate
      run: terraform validate
